flags: {}
packages:
- location: .
- location:
    git: https://github.com/stschiff/sequence-formats.git
    commit: 415a028b525c7b6832b7f1051432a415a4012df0
  extra-dep: true
extra-deps: []
resolver: lts-10.5
