flags: {}
packages:
- location: .
- location:
    git: https://github.com/stschiff/sequence-formats.git
    commit: 668c4e00abf16d13a50181792f02d2535cc0f6dd
  extra-dep: true
extra-deps: []
resolver: lts-10.5
