flags: {}
packages:
- location: .
- location:
    git: https://github.com/stschiff/sequence-formats.git
    commit: 721a61a188f52fd7eb6acd5197223e4938dba467
  extra-dep: true
extra-deps: []
resolver: lts-10.5
