flags: {}
packages:
- location: .
- location:
    git: https://github.com/stschiff/sequence-formats.git
    commit: c9ff27dc1582efe55cd35f42bc4b6c400376899d
  extra-dep: true
extra-deps: []
resolver: lts-10.5
